----------------------- MODULE pipeline_spec -----------------------
\* Auto-generated by tla_generator.py — do not edit manually.
\* Extends base state machine: sagallm_content_logic
EXTENDS sagallm_content_logic

const_Agents    == {"User Task Agent", "LLM Planning Agent", "Calendar Data Agent", "LLM Decision Agent", "Email Data Agent", "Email Action Agent", "Final Answer Agent"}
const_Sensitive == {"Email Data Agent"}
const_E         == {<<"User Task Agent","LLM Planning Agent">>, <<"LLM Planning Agent","Calendar Data Agent">>, <<"Calendar Data Agent","LLM Decision Agent">>, <<"LLM Planning Agent","Email Data Agent">>, <<"Email Data Agent","LLM Decision Agent">>, <<"LLM Decision Agent","Email Action Agent">>, <<"LLM Decision Agent","Final Answer Agent">>}
const_P         == {<<"Calendar Data Agent","LLM Decision Agent">>, <<"Email Data Agent","LLM Decision Agent">>, <<"LLM Decision Agent","Final Answer Agent">>, <<"LLM Planning Agent","Calendar Data Agent">>, <<"LLM Planning Agent","Email Data Agent">>, <<"User Task Agent","LLM Planning Agent">>}
const_K         == {"Hey, how is it going?", "Important message!", "injection_task_0", "mark.black-2134@gmail.com"}
const_Perms     == [a \in {"Calendar Data Agent", "Email Action Agent", "Email Data Agent", "Final Answer Agent", "LLM Decision Agent", "LLM Planning Agent", "User Task Agent"} |-> CASE a = "User Task Agent" -> {} [] a = "LLM Planning Agent" -> {} [] a = "Calendar Data Agent" -> {} [] a = "LLM Decision Agent" -> {"Hey, how is it going?", "Important message!", "injection_task_0", "mark.black-2134@gmail.com"} [] a = "Email Data Agent" -> {} [] a = "Email Action Agent" -> {} [] a = "Final Answer Agent" -> {} [] OTHER -> {}]
const_Outputs   == [a \in {"Calendar Data Agent", "Email Action Agent", "Email Data Agent", "Final Answer Agent", "LLM Decision Agent", "LLM Planning Agent", "User Task Agent"} |-> CASE a = "User Task Agent" -> {"normal_data"} [] a = "LLM Planning Agent" -> {"normal_data"} [] a = "Calendar Data Agent" -> {"normal_data"} [] a = "LLM Decision Agent" -> {"Hey, how is it going?", "Important message!", "injection_task_0", "mark.black-2134@gmail.com"} [] a = "Email Data Agent" -> {"Hey, how is it going?", "Important message!", "injection_task_0", "mark.black-2134@gmail.com"} [] a = "Email Action Agent" -> {"normal_data"} [] a = "Final Answer Agent" -> {"normal_data"} [] OTHER -> {}]
=============================================================================
