"""
advisor.py — Policy Advisor Orchestrator
==========================================
Implements the TLC → Rego auto-fix loop described in the SafeSagaLLM paper:

  1. Parse pipeline.yaml
  2. Generate Rego from policy section (P_tran + P_cont)
  3. Generate TLA+ spec from agents, execution_edges, allowed_transfers
  4. Run TLC via TLCVerifier
  5. For each violation:
       - Look up fix rule in tlc_to_opa.yaml
       - If auto_fixable: patch PipelineConfig in-memory → go to 2
       - If not fixable:  print guidance and stop
  6. Converge (zero violations) or report failure after max_iterations

Auto-fixable violations:
  DataIsolation       → remove the leaking (sender → receiver) edge from
                        allowed_transfers so the path is no longer in P
  ContentDataIsolation→ add the escaped keyword to sensitive_keywords

Not auto-fixable (structural / liveness):
  AtomicTermination, CompensationCompleteness, ExecutionOrderPreserved, Deadlock

Usage:
    advisor = PolicyAdvisor(tlc_jar="/path/to/tla2tools.jar")
    ok = advisor.run("pipeline.yaml", root_dir=".")
"""

import json
import re
import yaml
from dataclasses import dataclass, field
from pathlib import Path

from colorama import Fore, Style

from policy_advisor.tla_generator import TLASpec, write_spec
from policy_advisor.verifier import TLCVerifier, ViolationInfo, TLCResult
from policy_advisor.mapping.loader import MappingLoader

_MAPPING = MappingLoader()

# ── Rego template ─────────────────────────────────────────────────────────────
# Uses {{ / }} to escape literal braces inside an f-string.

_REGO_TEMPLATE = """\
# {stem}.rego — Auto-generated by advisor.py (SafeSagaLLM Policy Advisor)
# Policy: P_tran (path control) + P_cont (content control) + clearance (Bell-LaPadula No Write Down)
package sagallm.access_control

import future.keywords.in

default allow_transfer    := false
default reason            := "Transfer denied by default policy"
default matching_keywords := []
default filtered_content  := ""

# ── Clearance lattice (Bell-LaPadula No Write Down) ───────────────────────────
# public(0) < internal(1) < restricted(2)
#   public:     agents handling only publicly available information
#   internal:   agents handling need-to-know data (PII, account numbers, addresses)
#   restricted: agents handling auth/financial credentials (password, tokens, SSN)
# Rule: sender must NOT write down to a receiver with lower clearance level.
clearance_level := {{
    "public":     0,
    "internal":   1,
    "restricted": 2,
}}

# Per-agent clearance assignment (auto-generated from pipeline.yaml)
agent_clearance := {{
{agent_clearance}}}

# No Write Down: sender.level <= receiver.level
_clearance_ok if {{
    sender_level   := object.get(agent_clearance, input.sender, 0)
    receiver_level := object.get(agent_clearance, input.receiver, 0)
    clearance_level[sender_level] <= clearance_level[receiver_level]
}}

# P_cont: sensitive keyword set K (triggers line-level redaction)
sensitive_keywords := {{
{keywords}}}

# P_cont: per-receiver keyword allowlist (least privilege)
# Receivers absent from this map receive no sensitive keywords at all.
agent_keyword_permissions := {{
{keyword_perms}}}

# P_tran: authorized transfer edges (subset of execution graph E)
allowed_transfers := {{
{allowed_transfers}}}

# ── Content filtering (line-level) ────────────────────────────────────────────
_receiver_permitted := object.get(agent_keyword_permissions, input.receiver, set())

_line_needs_censor(line) if {{
    some kw in sensitive_keywords
    contains(line, kw)
    not kw in _receiver_permitted
}}

_censor_line(line) := "[Censored]" if {{
    _line_needs_censor(line)
}} else := line

_lines := split(input.content, "\\n") if {{ input.content }} else := []

_filtered_lines := [r |
    some i
    line := _lines[i]
    r := _censor_line(line)
]

filtered_content := concat("\\n", _filtered_lines) if {{ input.content }}

matching_keywords := {{kw |
    some kw in sensitive_keywords
    contains(input.content, kw)
    not kw in _receiver_permitted
}} if {{ input.content }}

# ── Authorization rule (P_tran ∧ clearance) ───────────────────────────────────
allow_transfer if {{
    allowed_transfers[input.sender][input.receiver]
    _clearance_ok
}}

reason := msg if {{
    not allow_transfer
    allowed_transfers[input.sender]
    not allowed_transfers[input.sender][input.receiver]
    msg := sprintf(
        "PATH_DENY: Agent '%v' is not permitted to transfer context to '%v'",
        [input.sender, input.receiver]
    )
}}

reason := msg if {{
    not allow_transfer
    not allowed_transfers[input.sender]
    msg := sprintf(
        "PATH_DENY: Unknown sender '%v' — transfer denied",
        [input.sender]
    )
}}

reason := msg if {{
    not allow_transfer
    allowed_transfers[input.sender][input.receiver]
    not _clearance_ok
    msg := sprintf(
        "CLEARANCE_DENY: No Write Down — sender '%v' has higher clearance than receiver '%v'",
        [input.sender, input.receiver]
    )
}}
"""


# ── Clearance auto-assignment ─────────────────────────────────────────────────
# Keyword sets for Bell-LaPadula clearance inference.
# Basis: OWASP A02:2021 (Cryptographic Failures / Sensitive Data Exposure)
#        + WebArena §3.2 (require_login → session credentials present)

_RESTRICTED_KW: frozenset[str] = frozenset({
    "password", "session_token", "auth_token", "cookie",
    "api_key", "access_token", "admin_credential", "repository_secret",
})
_INTERNAL_KW: frozenset[str] = frozenset({
    "email", "phone_number", "home_address",
    "credit_card", "card_number", "purchase_history", "shipping_address", "order_details",
    "private_message", "inbox_content", "user_session", "user_profile",
    "user_database", "transaction_log", "customer_email",
    "commit_hash", "location_history", "saved_places",
})
_CLEARANCE_RANK: dict[str, int] = {"public": 0, "internal": 1, "restricted": 2}
_CLEARANCE_NAME: list[str] = ["public", "internal", "restricted"]


def auto_assign_clearance(
    agents: list[str],
    agent_output_keywords: dict[str, list[str]],
    execution_edges: list[tuple[str, str]],
    sensitive_agents: list[str] | None = None,
    all_sensitive_keywords: list[str] | None = None,
) -> dict[str, str]:
    """
    Auto-assign Bell-LaPadula clearance (public / internal / restricted).

    Pass 1 — base level from output keyword categories:
      restricted : OWASP auth credentials (password, session/auth tokens, API keys)
      internal   : OWASP PII / account data (email, credit card, address, messages)
                   + any domain-specific keyword listed in all_sensitive_keywords
      public     : no sensitive keywords detected

    Pass 2 — taint propagation through execution_edges:
      Raises receiver's clearance to match sender level, so No Write Down holds
      across the full agent chain without manual annotation.
    """
    _sensitive_set = set(sensitive_agents or [])
    _domain_kw = set(all_sensitive_keywords or [])
    clearance: dict[str, str] = {}

    # Pass 1: base clearance from output keyword categories
    for agent in agents:
        kws = set(agent_output_keywords.get(agent, []))
        if kws & _RESTRICTED_KW:
            clearance[agent] = "restricted"
        elif kws & (_INTERNAL_KW | _domain_kw) or (agent in _sensitive_set and kws):
            clearance[agent] = "internal"
        else:
            clearance[agent] = "public"

    # Pass 2: taint propagation (raise receiver to match sender clearance)
    changed = True
    while changed:
        changed = False
        for src, dst in execution_edges:
            src_level = _CLEARANCE_RANK.get(clearance.get(src, "public"), 0)
            dst_level = _CLEARANCE_RANK.get(clearance.get(dst, "public"), 0)
            if src_level > dst_level:
                clearance[dst] = _CLEARANCE_NAME[src_level]
                changed = True

    return clearance


# ── Pipeline configuration ────────────────────────────────────────────────────

@dataclass
class PipelineConfig:
    agents: list
    agent_metadata: dict
    agent_clearance: dict                       # {agent: clearance_level_str}
    sensitive_agents: list
    execution_edges: list                       # list of (src, dst) tuples
    allowed_transfers: dict                     # {sender: [receiver, ...]}
    sensitive_keywords: list
    keyword_permissions: dict                   # {receiver: [keyword, ...]}
    agent_output_keywords: dict                 # {agent: [true output keyword, ...]}
    rego_output: str
    tla_output_dir: str


def load_pipeline(path) -> PipelineConfig:
    """Parse pipeline.yaml into a PipelineConfig dataclass."""
    data = yaml.safe_load(Path(path).read_text())

    agent_defs       = data["agents"]
    agents           = [a["name"] for a in agent_defs]
    sensitive_agents = [a["name"] for a in agent_defs if a.get("sensitive", False)]
    execution_edges  = [tuple(e) for e in data["execution_edges"]]

    policy              = data.get("policy", {})
    allowed_transfers   = {k: list(v) for k, v in policy.get("allowed_transfers", {}).items()}
    sensitive_keywords  = list(policy.get("sensitive_keywords", []))
    keyword_permissions = {k: list(v) for k, v in policy.get("keyword_permissions", {}).items()}
    configured_outputs  = policy.get("agent_output_keywords", {})
    agent_output_keywords = {}
    for agent_def in agent_defs:
        name = agent_def["name"]
        if name in configured_outputs:
            agent_output_keywords[name] = list(configured_outputs[name])
        elif "output_keywords" in agent_def:
            agent_output_keywords[name] = list(agent_def["output_keywords"])
        elif name in sensitive_agents:
            agent_output_keywords[name] = list(sensitive_keywords)
        else:
            agent_output_keywords[name] = ["normal_data"]

    # Auto-assign Bell-LaPadula clearance — replaces manual clearance: fields in YAML.
    # Uses keyword category + taint propagation through execution_edges.
    agent_clearance = auto_assign_clearance(
        agents, agent_output_keywords, list(execution_edges),
        sensitive_agents=sensitive_agents,
        all_sensitive_keywords=sensitive_keywords,
    )

    agent_metadata = {
        a["name"]: {
            "model": a.get("model", "gpt-4o"),
            "capability": a.get("capability", "general"),
            "clearance": agent_clearance.get(a["name"], "public"),
        }
        for a in agent_defs
    }

    return PipelineConfig(
        agents=agents,
        agent_metadata=agent_metadata,
        agent_clearance=agent_clearance,
        sensitive_agents=sensitive_agents,
        execution_edges=execution_edges,
        allowed_transfers=allowed_transfers,
        sensitive_keywords=sensitive_keywords,
        keyword_permissions=keyword_permissions,
        agent_output_keywords=agent_output_keywords,
        rego_output=data.get("rego_output", "src/policies/generated.rego"),
        tla_output_dir=data.get("tla_output_dir", "spec/generated"),
    )


# ── Rego generation ───────────────────────────────────────────────────────────

def generate_rego(cfg: PipelineConfig, stem: str = "generated") -> str:
    """Render a complete Rego policy string from PipelineConfig."""
    # Clearance: {agent: level_str} → Rego object literal
    clearance_parts = [
        f"    {json.dumps(agent)}: {json.dumps(level)}"
        for agent, level in cfg.agent_clearance.items()
    ]
    agent_clearance_str = ",\n".join(clearance_parts)

    kw_lines = "\n".join(f"    {json.dumps(kw)}," for kw in sorted(cfg.sensitive_keywords))

    perm_parts = []
    for agent, kws in cfg.keyword_permissions.items():
        kw_set = ", ".join(json.dumps(kw) for kw in kws)
        perm_parts.append(f"    {json.dumps(agent)}: {{{kw_set}}}")
    keyword_perms_str = ",\n".join(perm_parts)

    transfer_parts = []
    for sender in cfg.agents:
        receivers = cfg.allowed_transfers.get(sender, [])
        if receivers:
            recv_set = ", ".join(json.dumps(r) for r in receivers)
            transfer_parts.append(f"    {json.dumps(sender)}: {{{recv_set}}}")
        else:
            transfer_parts.append(f"    {json.dumps(sender)}: {{}}")
    allowed_transfers_str = ",\n".join(transfer_parts)

    return _REGO_TEMPLATE.format(
        stem=stem,
        agent_clearance=agent_clearance_str + "\n" if agent_clearance_str else "",
        keywords=kw_lines + "\n" if kw_lines else "",
        keyword_perms=keyword_perms_str + "\n" if keyword_perms_str else "",
        allowed_transfers=allowed_transfers_str + "\n" if allowed_transfers_str else "",
    )


# ── Pre-TLC structural validation ────────────────────────────────────────────

@dataclass
class ValidationError:
    """One structural problem found before TLC is invoked."""
    kind: str     # "unknown_agent" | "cycle" | "policy_agent_mismatch" | "policy_edge_not_in_graph"
    message: str
    hint: str     # what to edit in pipeline.yaml


def _validate_pipeline(cfg: PipelineConfig) -> list[ValidationError]:
    """
    Check pipeline.yaml structure WITHOUT running TLC.
    Catches problems that would cause Deadlock or ExecutionOrderPreserved
    violations before wasting a TLC run.

    Checks:
      1. Every agent name in execution_edges appears in agents list.
      2. execution_edges is acyclic (topological sort test).
      3. Every agent in allowed_transfers appears in agents list.
      4. allowed_transfers is a subset of execution_edges.
      5. Every agent in agent_output_keywords appears in agents list.
    """
    errors: list[ValidationError] = []
    agent_set = set(cfg.agents)

    # ── Check 1: unknown agents in execution_edges ────────────────────────────
    for src, dst in cfg.execution_edges:
        for name in (src, dst):
            if name not in agent_set:
                errors.append(ValidationError(
                    kind="unknown_agent",
                    message=f"'{name}' appears in execution_edges but is not in agents list.",
                    hint=f"Add '- name: \"{name}\"' under agents:, or fix the typo in execution_edges.",
                ))

    # ── Check 2: cycle detection via Kahn's BFS ───────────────────────────────
    from collections import deque, defaultdict
    in_degree: dict[str, int] = defaultdict(int)
    adjacency: dict[str, list[str]] = defaultdict(list)
    for src, dst in cfg.execution_edges:
        adjacency[src].append(dst)
        in_degree[dst] += 1
        in_degree.setdefault(src, 0)

    queue = deque(n for n in in_degree if in_degree[n] == 0)
    visited = 0
    while queue:
        node = queue.popleft()
        visited += 1
        for neighbor in adjacency[node]:
            in_degree[neighbor] -= 1
            if in_degree[neighbor] == 0:
                queue.append(neighbor)

    if visited < len(in_degree):
        # Identify the nodes stuck in a cycle
        cycle_nodes = [n for n in in_degree if in_degree[n] > 0]
        errors.append(ValidationError(
            kind="cycle",
            message=f"Cycle detected among agents: {cycle_nodes}",
            hint=(
                "execution_edges must form a DAG (no circular dependencies). "
                "Find and remove the edge that closes the cycle."
            ),
        ))

    # ── Check 3: unknown agents in allowed_transfers ──────────────────────────
    for sender, receivers in cfg.allowed_transfers.items():
        for name in [sender] + list(receivers):
            if name not in agent_set:
                errors.append(ValidationError(
                    kind="policy_agent_mismatch",
                    message=f"'{name}' appears in policy.allowed_transfers but is not in agents list.",
                    hint=f"Add '- name: \"{name}\"' under agents:, or fix the typo in policy.allowed_transfers.",
                ))

    # ── Check 4: allowed_transfers must be a subset of execution_edges ────────
    # The generated TLA+ model verifies D_actual = E ∩ P. If P contains an edge
    # outside E, TLC ignores it, while OPA would still allow it if runtime code
    # attempted the transfer.
    execution_edge_set = set(cfg.execution_edges)
    for sender, receivers in cfg.allowed_transfers.items():
        for receiver in receivers:
            if (
                sender in agent_set
                and receiver in agent_set
                and (sender, receiver) not in execution_edge_set
            ):
                errors.append(ValidationError(
                    kind="policy_edge_not_in_graph",
                    message=(
                        f"policy.allowed_transfers permits '{sender}' -> '{receiver}', "
                        "but that edge is not declared in execution_edges."
                    ),
                    hint=(
                        "Either add the edge to execution_edges if it is a real dependency, "
                        "or remove it from policy.allowed_transfers."
                    ),
                ))

    # ── Check 5: unknown agents in TLA output keyword model ───────────────────
    for agent in cfg.agent_output_keywords:
        if agent not in agent_set:
            errors.append(ValidationError(
                kind="policy_agent_mismatch",
                message=f"'{agent}' appears in policy.agent_output_keywords but is not in agents list.",
                hint=f"Add '- name: \"{agent}\"' under agents:, or fix the typo in policy.agent_output_keywords.",
            ))

    return errors


def _print_validation_errors(errors: list[ValidationError]) -> None:
    """Print structured validation errors with fix hints."""
    print(Fore.RED + f"\n  ✖  Pre-flight check failed — {len(errors)} issue(s) found:" + Style.RESET_ALL)
    for i, e in enumerate(errors, 1):
        print(Fore.RED + f"\n  [{i}] [{e.kind}] {e.message}" + Style.RESET_ALL)
        print(Fore.YELLOW + f"      → Fix: {e.hint}" + Style.RESET_ALL)
    print(Fore.RED + "\n  Edit pipeline.yaml and re-run." + Style.RESET_ALL)


# ── Fix application ───────────────────────────────────────────────────────────

def _extract_leaking_receiver(violation: ViolationInfo) -> str | None:
    """
    Parse TLC counterexample output to find which agent has sensitive_data
    in its promptContext.  Returns the agent name, or None if not found.
    """
    pattern = _MAPPING.compile_pattern("receiver")
    m = pattern.search(violation.excerpt)
    return m.group(1) if m else None


def _extract_all_leaking_keywords(cfg: PipelineConfig, violation: ViolationInfo) -> list[str]:
    """
    Find ALL secret keywords that cause a ContentDataIsolation violation.

    ContentDataIsolation is violated for every keyword in SecretKeywords that
    is absent from SensitiveKeywords (K) — ContentFiltered passes it through
    unchecked when kw ∉ K. Returning all missing keywords at once allows the
    advisor to fix the violation in a single iteration instead of one keyword
    per iteration.

    Falls back to excerpt scanning as a secondary check.
    """
    secret_keywords = {
        kw
        for agent in cfg.sensitive_agents
        for kw in cfg.agent_output_keywords.get(agent, [])
    }

    # Primary: all secret keywords absent from sensitive_keywords
    missing_from_k = [
        kw for kw in sorted(secret_keywords)
        if kw not in cfg.sensitive_keywords
    ]
    if missing_from_k:
        return missing_from_k

    # Secondary fallback: scan excerpt for quoted keyword tokens
    found = [
        kw for kw in sorted(secret_keywords, key=len, reverse=True)
        if json.dumps(kw) in violation.excerpt
    ]
    return found


def _apply_fix(cfg: PipelineConfig, violation: ViolationInfo) -> bool:
    """
    Attempt to auto-fix a TLC violation by mutating cfg in-place.
    Uses MappingLoader to look up the fix rule from tlc_to_opa.yaml.

    Returns True if a fix was applied, False if manual intervention is needed.
    """
    if not _MAPPING.is_opa_fixable(violation.name):
        msg = _MAPPING.action_on_violation(violation.name)
        print(Fore.RED + f"  [advisor] '{violation.name}' requires manual fix." + Style.RESET_ALL)
        print(Fore.RED + f"            {msg.strip()}" + Style.RESET_ALL)
        return False

    # Try to identify the leaking receiver from TLC counterexample
    receiver = _extract_leaking_receiver(violation)
    bad_sender: str | None = None
    in_E: bool | None = None

    if receiver:
        # Check if any sensitive agent is a declared upstream of receiver in E
        sensitive_upstreams = [
            src for src in cfg.sensitive_agents
            if (src, receiver) in cfg.execution_edges
        ]
        if sensitive_upstreams:
            bad_sender = sensitive_upstreams[0]
            in_E = True
        else:
            in_E = False

    fix_type = _MAPPING.decide_fix_type(violation.name, in_E=in_E, bad_sender=bad_sender)
    fix_spec  = _MAPPING.get_fix_spec(violation.name, fix_type)

    rego_field = fix_spec.get("rego_field", "")
    action     = fix_spec.get("action", "")

    # ── P_tran fix: remove sender → receiver from allowed_transfers ───────────
    if rego_field == "allowed_transfers" and action == "remove_receiver":
        fixed = False
        targets = [(bad_sender, receiver)] if bad_sender and receiver else [
            (src, dst)
            for src in cfg.sensitive_agents
            for dst in list(cfg.allowed_transfers.get(src, []))
        ]
        for src, dst in targets:
            if dst in cfg.allowed_transfers.get(src, []):
                print(
                    Fore.YELLOW
                    + f"  [advisor] P_tran fix: removing '{src}' → '{dst}' from allowed_transfers"
                    + Style.RESET_ALL
                )
                cfg.allowed_transfers[src] = [r for r in cfg.allowed_transfers[src] if r != dst]
                fixed = True
        return fixed

    # ── P_cont fix: add ALL missing keywords to sensitive_keywords at once ──────
    if rego_field == "sensitive_keywords" and action == "add_keyword":
        keywords = _extract_all_leaking_keywords(cfg, violation)
        if not keywords:
            print(
                Fore.YELLOW
                + f"  [advisor] P_cont fix needed, but no missing keywords could be identified. "
                + f"Add them to sensitive_keywords in pipeline.yaml, then re-run."
                + Style.RESET_ALL
            )
            print(Fore.YELLOW + f"  TLC excerpt:\n{violation.excerpt}" + Style.RESET_ALL)
            return False

        added = [kw for kw in keywords if kw not in cfg.sensitive_keywords]
        if added:
            print(
                Fore.YELLOW
                + f"  [advisor] P_cont fix: adding {len(added)} keyword(s) to sensitive_keywords: "
                + ", ".join(f"'{kw}'" for kw in added)
                + Style.RESET_ALL
            )
            cfg.sensitive_keywords.extend(added)
            return True

        print(
            Fore.YELLOW
            + f"  [advisor] all keywords already in sensitive_keywords; "
            + f"check keyword_permissions for the leaking receiver."
            + Style.RESET_ALL
        )
        return False

    print(Fore.YELLOW + f"  [advisor] No handler for fix_type='{fix_type}'" + Style.RESET_ALL)
    return False


# ── Main advisor class ────────────────────────────────────────────────────────

class GuardCoordinator:
    def __init__(self, tlc_jar=None, max_iterations: int = 5):
        self.verifier       = TLCVerifier(tlc_jar=tlc_jar)
        self.max_iterations = max_iterations

    def run(self, pipeline_path, root_dir=".") -> bool:
        """
        Execute the TLC → Rego fix loop for the given pipeline.yaml.

        Args:
            pipeline_path : path to pipeline.yaml
            root_dir      : project root for resolving rego_output / tla_output_dir

        Returns:
            True  — all invariants verified, final Rego written to rego_output
            False — violation could not be auto-fixed or max iterations reached
        """
        root = Path(root_dir)
        cfg  = load_pipeline(pipeline_path)

        print(Fore.CYAN + f"\n{'='*60}")
        print(f"  SafeSagaLLM Policy Advisor")
        print(f"  pipeline : {pipeline_path}")
        print(f"{'='*60}" + Style.RESET_ALL)

        # Pre-flight: catch structural errors before wasting a TLC run
        print(Fore.CYAN + "  [preflight] validating pipeline structure..." + Style.RESET_ALL)
        errors = _validate_pipeline(cfg)
        if errors:
            _print_validation_errors(errors)
            return False
        print(Fore.GREEN + "  [preflight] OK" + Style.RESET_ALL)

        for iteration in range(1, self.max_iterations + 1):
            print(Fore.CYAN + f"\n── Iteration {iteration} {'─'*(48 - len(str(iteration)))}" + Style.RESET_ALL)

            # Step 1: Generate Rego
            rego_path = root / cfg.rego_output
            rego_path.parent.mkdir(parents=True, exist_ok=True)
            rego_path.write_text(generate_rego(cfg, stem=rego_path.stem))
            print(Fore.GREEN + f"  [rego]     written → {rego_path}" + Style.RESET_ALL)

            # Step 2: Build TLA+ spec
            policy_edges = [
                (sender, receiver)
                for sender, receivers in cfg.allowed_transfers.items()
                for receiver in receivers
            ]
            spec = TLASpec(
                module_name="pipeline_spec",
                agents=cfg.agents,
                sensitive_agents=cfg.sensitive_agents,
                execution_edges=list(cfg.execution_edges),
                policy_edges=policy_edges,
                sensitive_keywords=cfg.sensitive_keywords,
                keyword_permissions=cfg.keyword_permissions,
                agent_output_keywords=cfg.agent_output_keywords,
                agent_clearance=cfg.agent_clearance,
            )
            tla_dir          = root / cfg.tla_output_dir
            tla_path, cfg_path = write_spec(spec, tla_dir)
            print(Fore.GREEN + f"  [tla+]     written → {tla_path}" + Style.RESET_ALL)

            # Step 3: Run TLC
            print(Fore.CYAN + f"  [tlc]      running model checker..." + Style.RESET_ALL)
            try:
                result: TLCResult = self.verifier.run(tla_path, cfg_path)
            except RuntimeError as e:
                print(Fore.RED + f"  [tlc]      ERROR: {e}" + Style.RESET_ALL)
                return False

            # Step 4: Evaluate
            if result.success:
                print(Fore.GREEN + f"\n  ✅ All invariants hold — policy verified!" + Style.RESET_ALL)
                print(Fore.GREEN + f"  Final Rego → {rego_path}" + Style.RESET_ALL)
                return True

            print(Fore.RED + f"\n  ⚠️  {len(result.violations)} violation(s):" + Style.RESET_ALL)
            any_fixed    = False
            needs_manual = []

            for v in result.violations:
                print(Fore.RED + f"    • [{v.kind}] {v.name}" + Style.RESET_ALL)
                if _apply_fix(cfg, v):
                    any_fixed = True
                else:
                    needs_manual.append(v)

            if needs_manual:
                print(Fore.RED + "\n  ❌ Manual intervention required. Stopping." + Style.RESET_ALL)
                return False

            if not any_fixed:
                print(Fore.RED + "  ❌ No fix could be applied. Stopping." + Style.RESET_ALL)
                return False

        print(Fore.RED + f"\n  ❌ Did not converge after {self.max_iterations} iterations." + Style.RESET_ALL)
        return False
