"""
tla_generator.py — TLA+ Specification Generator
=================================================
Converts pipeline.yaml data into TLA+ spec (.tla) and config (.cfg) files
that TLC model checker can verify.

The generated spec EXTENDS sagallm_content_logic (the base state machine)
and instantiates it with the pipeline's agents, edges, and policy graph.

Generated files per run:
  <output_dir>/pipeline_spec.tla   — constants instantiation
  <output_dir>/pipeline_spec.cfg   — CONSTANTS / INVARIANTS / PROPERTIES
  <output_dir>/sagallm_content_logic.tla  — copied base module for EXTENDS resolution
"""

import shutil
from dataclasses import dataclass
from pathlib import Path

# Path to the base TLA+ module (relative to this file's location in src/)
_BASE_MODULE_NAME = "sagallm_content_logic"
_BASE_MODULE_SRC = (
    Path(__file__).parent
    / "tla"
    / f"{_BASE_MODULE_NAME}.tla"
)


@dataclass
class TLASpec:
    """Structured input for TLA+ generation."""
    module_name: str
    agents: list[str]
    sensitive_agents: list[str]
    execution_edges: list[tuple[str, str]]   # E: structural dependency graph
    policy_edges: list[tuple[str, str]]      # P: OPA-allowed transfer paths
    sensitive_keywords: list[str]            # policy K: keywords Rego redacts
    keyword_permissions: dict[str, list[str]] # receiver -> permitted keywords
    agent_output_keywords: dict[str, list[str]] # true keywords each agent may emit
    agent_clearance: dict[str, str]          # Bell-LaPadula clearance per agent


# ── Formatting helpers ────────────────────────────────────────────────────────

def _q(s: str) -> str:
    """Wrap string in TLA+ double quotes."""
    return f'"{s}"'


def _tla_set(items: list[str]) -> str:
    """Render a Python list as a TLA+ set literal: {a, b, c}."""
    if not items:
        return "{}"
    return "{" + ", ".join(items) + "}"


def _tla_tuple_set(pairs: list[tuple[str, str]]) -> str:
    """Render (src, dst) pairs as a TLA+ set of 2-tuples: {<<a,b>>, <<c,d>>}."""
    if not pairs:
        return "{}"
    elems = [f'<<{_q(s)},{_q(d)}>>' for s, d in pairs]
    return "{" + ", ".join(elems) + "}"


def _tla_string_set(items: list[str]) -> str:
    """Render strings as a TLA+ set literal."""
    return _tla_set([_q(i) for i in sorted(set(items))])


def _tla_function_map(domain: list[str], mapping: dict[str, list[str]]) -> str:
    """Render a total TLA+ function over domain with set-valued entries."""
    clauses = [
        f'a = {_q(agent)} -> {_tla_string_set(mapping.get(agent, []))}'
        for agent in domain
    ]
    return "[a \\in " + _tla_string_set(domain) + " |-> CASE " + " [] ".join(clauses) + " [] OTHER -> {}]"


# ── File content generators ───────────────────────────────────────────────────

# Clearance level ordering for TLA+ (Bell-LaPadula No Write Down)
# 3-level lattice: public(0) < internal(1) < restricted(2)
_CLEARANCE_LEVELS = {"public": 0, "internal": 1, "restricted": 2}


def _tla_clearance_map(agents: list[str], clearance: dict[str, str]) -> str:
    """
    Render agent clearance as a TLA+ function mapping agent -> numeric level.
    e.g. [a in {"A","B"} |-> CASE a = "A" -> 2 [] a = "B" -> 1 [] OTHER -> 1]
    """
    clauses = [
        f'a = {_q(agent)} -> {_CLEARANCE_LEVELS.get(clearance.get(agent, "internal"), 1)}'
        for agent in agents
    ]
    return "[a \\in " + _tla_string_set(agents) + " |-> CASE " + " [] ".join(clauses) + " [] OTHER -> 1]"


def generate_tla(spec: TLASpec) -> str:
    """Return .tla file content for the given spec."""
    agents_set    = _tla_set([_q(a) for a in spec.agents])
    sensitive_set = _tla_set([_q(a) for a in spec.sensitive_agents])
    e_set         = _tla_tuple_set(spec.execution_edges)
    p_set         = _tla_tuple_set(spec.policy_edges)
    kw_set        = _tla_string_set(spec.sensitive_keywords)
    perms_fn      = _tla_function_map(spec.agents, spec.keyword_permissions)
    outputs_fn    = _tla_function_map(spec.agents, spec.agent_output_keywords)
    clearance_fn  = _tla_clearance_map(spec.agents, spec.agent_clearance)

    return (
        f"----------------------- MODULE {spec.module_name} -----------------------\n"
        f"\\* Auto-generated by tla_generator.py — do not edit manually.\n"
        f"\\* Extends base state machine: {_BASE_MODULE_NAME}\n"
        f"EXTENDS {_BASE_MODULE_NAME}\n"
        f"\n"
        f"const_Agents    == {agents_set}\n"
        f"const_Sensitive == {sensitive_set}\n"
        f"const_E         == {e_set}\n"
        f"const_P         == {p_set}\n"
        f"const_K         == {kw_set}\n"
        f"const_Perms     == {perms_fn}\n"
        f"const_Outputs   == {outputs_fn}\n"
        f"const_Clearance == {clearance_fn}\n"
        f"=============================================================================\n"
    )


def generate_cfg(spec: TLASpec) -> str:
    """Return .cfg file content for the given spec."""
    return (
        f"\\* Auto-generated by tla_generator.py\n"
        f"SPECIFICATION Spec\n"
        f"CONSTANTS\n"
        f"    Agents              <- const_Agents\n"
        f"    SensitiveAgents     <- const_Sensitive\n"
        f"    E                   <- const_E\n"
        f"    P                   <- const_P\n"
        f"    SensitiveKeywords   <- const_K\n"
        f"    KeywordPermissions  <- const_Perms\n"
        f"    AgentOutputKeywords <- const_Outputs\n"
        f"    AgentClearance      <- const_Clearance\n"
        f"INVARIANTS DataIsolation ContentDataIsolation ClearanceViolation\n"
        f"PROPERTIES AtomicTermination CompensationCompleteness\n"
    )


# ── Public API ────────────────────────────────────────────────────────────────

def write_spec(spec: TLASpec, output_dir: str | Path) -> tuple[Path, Path]:
    """
    Write .tla and .cfg to output_dir.
    Also copies sagallm_content_logic.tla into output_dir so TLC can resolve EXTENDS.

    Returns:
        (tla_path, cfg_path)

    Raises:
        FileNotFoundError: if the base module cannot be located.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    tla_path = out / f"{spec.module_name}.tla"
    cfg_path = out / f"{spec.module_name}.cfg"

    tla_path.write_text(generate_tla(spec))
    cfg_path.write_text(generate_cfg(spec))

    # Copy base module so TLC resolves EXTENDS without needing -lib flags
    base_dst = out / f"{_BASE_MODULE_NAME}.tla"
    if not _BASE_MODULE_SRC.exists():
        raise FileNotFoundError(
            f"Base TLA+ module not found at:\n  {_BASE_MODULE_SRC}\n"
            f"Copy sagallm_content_logic.tla to that path or update _BASE_MODULE_SRC."
        )
    shutil.copy(_BASE_MODULE_SRC, base_dst)

    return tla_path, cfg_path
