----------------------- MODULE pipeline_spec -----------------------
\* Auto-generated by tla_generator.py — do not edit manually.
\* Extends base state machine: sagallm_content_logic
EXTENDS sagallm_content_logic

const_Agents    == {"User Information Agent", "Travel Planning Agent", "Regulation Compliance Agent", "Final Booking Agent", "Audit Agent"}
const_Sensitive == {"User Information Agent", "Final Booking Agent"}
const_E         == {<<"User Information Agent","Travel Planning Agent">>, <<"Travel Planning Agent","Regulation Compliance Agent">>, <<"Regulation Compliance Agent","Final Booking Agent">>, <<"Final Booking Agent","Audit Agent">>, <<"User Information Agent","Final Booking Agent">>}
const_P         == {<<"Travel Planning Agent","Regulation Compliance Agent">>, <<"Regulation Compliance Agent","Final Booking Agent">>}
const_K         == {"credit_card_number", "passport_number"}
const_Perms     == [a \in {"Audit Agent", "Final Booking Agent", "Regulation Compliance Agent", "Travel Planning Agent", "User Information Agent"} |-> CASE a = "User Information Agent" -> {} [] a = "Travel Planning Agent" -> {} [] a = "Regulation Compliance Agent" -> {} [] a = "Final Booking Agent" -> {"credit_card_number", "passport_number"} [] a = "Audit Agent" -> {} [] OTHER -> {}]
const_Outputs   == [a \in {"Audit Agent", "Final Booking Agent", "Regulation Compliance Agent", "Travel Planning Agent", "User Information Agent"} |-> CASE a = "User Information Agent" -> {"credit_card_number", "passport_number"} [] a = "Travel Planning Agent" -> {"normal_data"} [] a = "Regulation Compliance Agent" -> {"normal_data"} [] a = "Final Booking Agent" -> {"credit_card_number", "passport_number"} [] a = "Audit Agent" -> {"normal_data"} [] OTHER -> {}]
=============================================================================
