#!/usr/bin/env python3
"""
run_pipeline.py — SafeSagaLLM Pipeline Executor
=================================================
Reads a pipeline.yaml (generated by run_planner.py or written manually)
and executes the multi-agent Saga pipeline with OPA enforcement.

Agents are instantiated from the yaml's backstory / task_description fields
and executed in topological order by the Saga coordinator.

Usage:
    python src/run_pipeline.py experiments/generated_pipeline.yaml
    python src/run_pipeline.py experiments/generated_pipeline.yaml --no-opa
    python src/run_pipeline.py experiments/generated_pipeline.yaml --report
"""

import argparse
import sys
from pathlib import Path

import yaml
from colorama import Fore, Style

sys.path.insert(0, str(Path(__file__).parent))

from multi_agent.agent import Agent
from multi_agent.saga import Saga


def load_and_run(pipeline_path: Path, enforce_opa: bool = True, report: bool = False, show_outputs: bool = False):
    """
    Parse pipeline.yaml, build Agent objects, wire dependencies,
    and run the Saga coordinator.

    Args:
        pipeline_path : path to pipeline.yaml
        enforce_opa   : whether to enforce OPA on transfers (default: True)
        report        : whether to print transfer audit report after run
    """
    data = yaml.safe_load(pipeline_path.read_text(encoding="utf-8"))

    agent_defs   = data.get("agents", [])
    edges        = [tuple(e) for e in data.get("execution_edges", [])]

    print(Fore.CYAN + "\n" + "=" * 60)
    print("  SafeSagaLLM Pipeline Executor")
    print(f"  pipeline : {pipeline_path}")
    print(f"  OPA      : {'enabled' if enforce_opa else 'disabled (baseline)'}")
    print("=" * 60 + Style.RESET_ALL)

    # ── Build Agent objects ────────────────────────────────────────────────────
    agent_map: dict[str, Agent] = {}
    for a in agent_defs:
        name = a["name"]
        agent_map[name] = Agent(
            name=name,
            backstory=a.get("backstory", f"You are {name}."),
            task_description=a.get("task_description", "Complete your assigned task."),
            task_expected_output=a.get("task_expected_output", ""),
            llm=a.get("model", "gpt-4o"),
            capability=a.get("capability", "general"),
            clearance=a.get("clearance", "internal"),
            mock_output=a.get("mock_output"),
        )

    print(Fore.CYAN + f"  agents   : {len(agent_map)}" + Style.RESET_ALL)
    for agent in agent_map.values():
        print(
            Fore.CYAN
            + f"    - {agent.name} | model={agent.model} | "
              f"capability={agent.capability} | clearance={agent.clearance}"
            + Style.RESET_ALL
        )

    # ── Wire execution dependencies (>> operator) ──────────────────────────────
    for src_name, dst_name in edges:
        if src_name not in agent_map or dst_name not in agent_map:
            print(Fore.RED + f"  ❌ Unknown agent in execution_edges: {src_name} → {dst_name}" + Style.RESET_ALL)
            sys.exit(1)
        agent_map[src_name] >> agent_map[dst_name]

    agents = list(agent_map.values())

    # ── Run via Saga coordinator ───────────────────────────────────────────────
    saga = Saga()
    saga.enforce_opa = enforce_opa
    saga.transaction_manager(agents)
    saga.saga_coordinator(with_rollback=True)

    # ── Reports ───────────────────────────────────────────────────────────────
    if show_outputs:
        saga.intra_agent()
    if report:
        saga.report_transfers()
        saga.report_dependency_vs_transfer()

    # ── Machine-readable exposure summary (parsed by run_experiment.py) ────────
    # Prints each agent's received context so downstream analysis can check
    # whether sensitive keywords reached unauthorized agents.
    import json as _json
    exposure_data = {}
    for agent in agents:
        exposure_data[agent.name] = agent.context or ""
    print(f"EXPOSURE_JSON:{_json.dumps(exposure_data)}")


def main():
    parser = argparse.ArgumentParser(
        description="SafeSagaLLM Pipeline Executor — run agents from pipeline.yaml",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "pipeline",
        help="Path to pipeline.yaml",
    )
    parser.add_argument(
        "--no-opa",
        action="store_true",
        help="Disable OPA enforcement (baseline mode — all transfers allowed)",
    )
    parser.add_argument(
        "--report",
        action="store_true",
        help="Print OPA transfer audit report and D_actual = E ∩ P table after run",
    )
    parser.add_argument(
        "--show-outputs",
        action="store_true",
        help="Print each agent's LLM output after run",
    )

    args = parser.parse_args()

    pipeline_path = Path(args.pipeline)
    if not pipeline_path.exists():
        print(f"Error: pipeline file not found: {pipeline_path}", file=sys.stderr)
        sys.exit(1)

    load_and_run(
        pipeline_path=pipeline_path,
        enforce_opa=not args.no_opa,
        report=args.report,
        show_outputs=args.show_outputs,
    )


if __name__ == "__main__":
    main()
