# conference_trip_booking.rego — Auto-generated by advisor.py (SafeSagaLLM Policy Advisor)
# Policy: P_tran (path control) + P_cont (content control)
package sagallm.access_control

import future.keywords.in

default allow_transfer    := false
default reason            := "Transfer denied by default policy"
default matching_keywords := []
default filtered_content  := ""

# P_cont: sensitive keyword set K (triggers line-level redaction)
sensitive_keywords := {
    "credit_card_number",
    "passport_number",
}

# P_cont: per-receiver keyword allowlist (least privilege)
# Receivers absent from this map receive no sensitive keywords at all.
agent_keyword_permissions := {
    "Final Booking Agent": {"passport_number", "credit_card_number"}
}

# P_tran: authorized transfer edges (subset of execution graph E)
allowed_transfers := {
    "User Information Agent": {"Final Booking Agent"},
    "Travel Options Agent": {"Constraint Validation Agent"},
    "Constraint Validation Agent": {"Final Booking Agent"},
    "Final Booking Agent": {}
}

# ── Content filtering (line-level) ────────────────────────────────────────────
_receiver_permitted := object.get(agent_keyword_permissions, input.receiver, set())

_line_needs_censor(line) if {
    some kw in sensitive_keywords
    contains(line, kw)
    not kw in _receiver_permitted
}

_censor_line(line) := "[Censored]" if {
    _line_needs_censor(line)
} else := line

_lines := split(input.content, "\n") if { input.content } else := []

_filtered_lines := [r |
    some i
    line := _lines[i]
    r := _censor_line(line)
]

filtered_content := concat("\n", _filtered_lines) if { input.content }

matching_keywords := {kw |
    some kw in sensitive_keywords
    contains(input.content, kw)
    not kw in _receiver_permitted
} if { input.content }

# ── Authorization rule ────────────────────────────────────────────────────────
allow_transfer if {
    allowed_transfers[input.sender][input.receiver]
}

reason := msg if {
    not allow_transfer
    allowed_transfers[input.sender]
    not allowed_transfers[input.sender][input.receiver]
    msg := sprintf(
        "PATH_DENY: Agent '%v' is not permitted to transfer context to '%v'",
        [input.sender, input.receiver]
    )
}

reason := msg if {
    not allow_transfer
    not allowed_transfers[input.sender]
    msg := sprintf(
        "PATH_DENY: Unknown sender '%v' — transfer denied",
        [input.sender]
    )
}
